captainVersion: 4
services:
  $$cap_appname:
    image: 0data/bind:latest
    volumes:
      - $$cap_appname-data:/app/__persistent
    restart: always
    caproverExtra:
      containerHttpPort: 3000
    environment:
      BIND_SECRET: $$cap_bind_secret
caproverOneClickApp:
  instructions:
    end: Bind is available as $$cap_appname. Next configure your domains.
  displayName: Bind
  description: Git-backed web apps.
  documentation: See documentation for details https://bind.0data.app
  variables:
    - id: $$cap_bind_secret
      label: Secret
      validRegex: /.{1,}/
      description: "Used to encrypt credentials. Generate one via `openssl rand -hex 32`, or use Better Auth's [Generate Secret](https://better-auth.com/docs/installation#set-environment-variables) button."
