captainVersion: 4
services:
  $$cap_appname:
    image: 0data/bind:latest
    volumes:
      - $$cap_appname-data:/app/__persistent
    restart: always
    caproverExtra:
      containerHttpPort: 3000
caproverOneClickApp:
  instructions:
    end: Bind is deployed and available as $$cap_appname. 
  displayName: Bind
  description: Git personal data store for web apps.
  documentation: See documentation for details https://bind.0data.app
